title: Major League Bettor
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
description: 6-5 (+0.77u)
color:
  saturation: 0.129824961302802
  brandStrength: 0.7064155095722526
  rhythmicContrast: 0.8598808201495558
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  lightness: 0.6296706018038094
navigation:
  - name: Intro
    id: 41da0199-917a-40c8-9232-fb4e9b080b99
    type: content
  - name: Running Totals
    id: 0524c3ef-e6d6-4167-b0cf-c10c884cf4d3
    type: content
  - name: The Model
    id: 5a76c552-5ae7-4f5c-93b6-564d6afbd333
    type: content
analytics:
  google: UA-83471006-1
favicon: null
name: Major League Bettor
logo: null
typography_spectrum: 0.3851635153405368
layout_spectrum: 0.2293233
